[package]
name = "cell_solver"
version = "0.1.0"
authors = ["William <william.lnx@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray="0.13.0"
itertools="0.8.2"
plotters = "0.3"
